name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Clone repo
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v2
        name: Get JDK
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build website flavor of the APK, run lint and tests
        run: sudo ./gradlew buildWebsiteRelease lint test
